version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html/
    container_name: askbiz-web
